### ISSUE TITLE
Add color hex values to README

### ISSUE THREAD

**Issue by alexlafroscia** [bluz71/vim-nightfly-guicolors#1]
Hey! I saw Nightfly on Reddit the other day and am checking it out. It's really great! Very nice work!

I was wondering if you would mind adding the hex values for each color to the table in the README. I'm working on setting up some of my other tools to use the Nightfly color palette as well, and having the hex next to the name and "swatch" for each of them would be really helpful!

In the meantime, I'm reading them from here

https://github.com/bluz71/vim-nightfly-guicolors/blob/7580e56103db6f7c7e92c7c795634663581dff06/colors/nightfly.vim#L49-L75

**Comment by bluz71** [comment]
A table with RGB values and swatches now exists towards the bottom of the README.

Cheers.

**Comment by alexlafroscia** [comment]
Thanks!
