### ISSUE TITLE
fzf.vim displaying wrong colors

### ISSUE THREAD

**Issue by raminos** [bluz71/vim-nightfly-guicolors#10]
Hey Dennis,

thanks for this fantastic theme. I really love the color composition! The only problem that I'm having is that my fzf plugin is not handling the colors correctly. Is this the case for you as well? 🤔 

## Screenshot
<img width="1359" alt="Screenshot 2020-10-10 at 20 19 33" src="https://user-images.githubusercontent.com/47226721/95662265-eb131280-0b35-11eb-81cf-5e1b2efcacc6.png">

## Replication:
- iTerm2 with nightfly theme
- nvim with nightfly theme
- fzf.vim with the recommended customization for themes:
```
let g:fzf_colors =
\ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }
```

Sorry to bother you with this 🙃

**Comment by bluz71** [comment]
Which colors look wrong?

The preview box on the right side? Noting that the colors inside that box are controlled by the viewer used to render the preview. For example the `bat` tool uses its own theme system.

**Comment by raminos** [comment]
I think I'm doing something wrong. I expected the popups background color to be the same as the overall background color 😅 .

**Comment by bluz71** [comment]
Oh I see it now.

Yes, something is amiss.

Which version of Vim/Neovim are you using?

**Comment by raminos** [comment]
I run nvim in version v0.4.3.

**Comment by bluz71** [comment]
There are some issues with Neovim 0.4.x with respect to terminal colors when `termguicolors` are set.

Is you terminal theme different to nightfly?

I myself am using Neovim 0.5 nightly, and it does not have the same issue.

**Comment by raminos** [comment]
I have `termguicolors` set to true. So there could be an issue. I will check out the nightly. I run your nightfly iterm file for my terminal colors.

**Comment by bluz71** [comment]
Hmmm, if you are using the nightfly terminal theme then I would not expect the result you are seeing.

I will run some tests and report back.

Note I do have a Mac and I used to run iTerm2, so it is a combination I am familiar with.

**Comment by raminos** [comment]
damn I hate all these coloring issues in the terminal 😅 . Seems like the nightly is not available yet for macos?! I will try it again in the coming days and then get back to you with the result 😊

**Comment by bluz71** [comment]
Nightly is available via Homebrew, it’s what I use.

**Comment by bluz71** [comment]
I just tested with Neovim 4.4 with your `fzf` settings from the first post, no issues:

<img width="585" alt="fzf" src="https://user-images.githubusercontent.com/11382509/95668882-5821b900-0bc5-11eb-9f2f-85791eb6f910.png">

iTerm2 and Alacritty both are setting the correct background color in `fzf` when using `nightfly`. Note, my terminal theme is not nightfly, I use my other theme moonfly as the terminal theme.

For the moment I am not sure what is going on with your setup. Quite strange. You may have to strip things back and get a minimal repeatable test case.

**Comment by raminos** [comment]
Yeah I reset all my color changes and you were right 😬 . Damn I'm very sorry!
It was this line that brought me so much trouble:
```
 hi Normal ctermbg=NONE guibg=NONE
```
I think I set it originally with vim 😅 .
