### ISSUE TITLE
barbar.nvim colors are off

### ISSUE THREAD

**Issue by Strayer** [bluz71/vim-nightfly-guicolors#11]
I was recently playing around with [romgrk/barbar.nvim](https://github.com/romgrk/barbar.nvim) but discovered that the colors are way off with nightfly:

<img width="442" alt="grafik" src="https://user-images.githubusercontent.com/310624/98729968-f018eb00-239b-11eb-8d50-89a0f8ac32ec.png">

I played a bit the the `Buffer*` colors used by barbar.nvim based on the line number colors and got to something like this, which I think looks a bit better:

<img width="440" alt="grafik" src="https://user-images.githubusercontent.com/310624/98732673-bfd34b80-239f-11eb-8e61-70ae585dc807.png">

```
exec 'highlight TablineFill guibg=bg'
exec 'highlight BufferCurrent cterm=none guibg=' . s:dark_blue . ' guifg=' . s:white . ' gui=none'
exec 'highlight BufferCurrentSign cterm=none guibg=' . s:dark_blue . ' guifg=' . s:blue . ' gui=none'
exec 'highlight BufferVisible cterm=none guibg=' . s:dark_blue . ' guifg=' . s:steel_blue . ' gui=none'
exec 'highlight BufferVisibleSign cterm=none guibg=' . s:dark_blue . ' guifg=' . s:steel_blue . ' gui=none'
exec 'highlight BufferInactive cterm=none guibg=bg guifg=' . s:steel_blue . ' gui=none'
exec 'highlight BufferInactiveSign cterm=none guibg=bg guifg=' . s:steel_blue . ' gui=none'
```

I don't really like the way the "tab line" looks with the default Tabline colors, but I guess it would fit the theme better if they'd match airline and friends. In the case of barbar I find the Tabline colors too distracting and like how it blends in more like in my screenshot above.

I'd love to open a PR for this, but would like to ask for your feedback first, since this is obviously very subjective.

Otherwise thanks for making this. I'd love to send a small donation for a coffee/beer/whateveryoulike if you're interested!

**Comment by bluz71** [comment]
Adding in colors for `barbar.nvim` is fine via plugin specific highlight groups. PR is welcome.

However, the following setting listed above is a no go:

```viml
exec 'highlight TablineFill guibg=bg'
```

That breaks the tabline for stock installations as seen here:

![Tabline](https://user-images.githubusercontent.com/11382509/98760413-526afd80-2427-11eb-90fd-9467e9e0dd9f.png)

I already set `TablineFill` to:

```viml
exec 'highlight TablineFill cterm=none guibg=' . s:slate_blue . ' guifg=' . s:slate_blue . ' gui=none'
```

That should remain as is.

**Comment by Strayer** [comment]
> However, the following setting listed above is a no go

I absolutely agree, I was just testing things out. I'd rather provide a patch to barbar.nvim for having another variable that only uses `TablineFill` as a fallback, like the other variables.

I'll look into this a bit more. Thanks for the feedback!

**Comment by Strayer** [comment]
<img width="998" alt="grafik" src="https://user-images.githubusercontent.com/310624/98816417-ed180c00-2428-11eb-9f8f-f8450b0ac022.png">

What do you think about this? I'm not all too great with colors, but I think it fits the original style of barbar.nvim very well while staying mostly true to the default tabline of nightfly.

```
exec 'highlight BufferCurrent      guibg=' . s:dark_blue . '  guifg=' . s:white
exec 'highlight BufferCurrentMod   guibg=' . s:dark_blue . '  guifg=' . s:tan
exec 'highlight BufferCurrentSign  guibg=' . s:dark_blue . '  guifg=' . s:blue
exec 'highlight BufferVisible      guibg=' . s:dark_blue . '  guifg=' . s:grey_blue
exec 'highlight BufferVisibleMod   guibg=' . s:dark_blue . '  guifg=' . s:tan
exec 'highlight BufferVisibleSign  guibg=' . s:dark_blue . '  guifg=' . s:grey_blue
exec 'highlight BufferInactive     guibg=' . s:slate_blue . ' guifg=' . s:grey_blue
exec 'highlight BufferInactiveMod  guibg=' . s:slate_blue . ' guifg=' . s:tan
exec 'highlight BufferInactiveSign guibg=' . s:slate_blue . ' guifg=' . s:cadet_blue
```

I can't figure out why some of the icons have an incorrect background, I think this may be a bug in barbar.nvim.

If you think the colors are fine, I'll try to resolve the icon background issue and open a PR.

**Comment by bluz71** [comment]
@Strayer,

The barbar.nvim theme colors are fine. Go ahead and open a PR.

I will then try and port those colors over to my other [moonfly](https://github.com/bluz71/vim-moonfly-colors) theme. I like to keep the two color schemes in synchronization.

Best regards.

**Comment by bluz71** [comment]
@Strayer,

Is it still your intention to produce a PR?

I would like to get this issue off the books soonish, if possible.

Regards.

**Comment by Strayer** [comment]
Sorry, this completely went off my radar. I'll get to this today.
