### ISSUE TITLE
TODO labels are not readable

### ISSUE THREAD

**Issue by dbalatero** [bluz71/vim-nightfly-guicolors#13]
![image](https://user-images.githubusercontent.com/59429/107879732-93503380-6ea8-11eb-8c02-852cfe332304.png)

Hello! I'm finding my TODO labels in comments to be unreadable. Wondering if I have a terminal color problem or if this is broken for you as well?

**Comment by bluz71** [comment]
Here is what TODOs look like for me in Neovim when run on Alacritty:

![nightfly-todo](https://user-images.githubusercontent.com/11382509/107906238-b8c26780-6fa4-11eb-95de-2d0bc4f41a1b.png)

It looks like you are running with transparency enabled, correct?

**Comment by bluz71** [comment]
I have just committed a change where I explicitly set the TODO foreground color.

I think that should fix your issue. Give it a try and let me know.

**Comment by dbalatero** [comment]
@bluz71 Thanks for the update! It looks to have cleared the TODO highlight:

![image](https://user-images.githubusercontent.com/59429/107956479-38344480-6f6d-11eb-94d5-420f38a9833c.png)

This is definitely better than before but curious if that was the intention to drop the highlight?

**Comment by bluz71** [comment]
No, todos should be black text on yellow as seen here (with my recent update):

![todo](https://user-images.githubusercontent.com/11382509/108029089-fdbbcc00-7080-11eb-8943-3687bdf5b019.png)

Are you using transparency? If you are then it may be the case that this is simply not fixable when in that mode. It may be your terminal that is changing the colors. You should pass on your details to see if I can repeat it.

Note, my nightfly and moonfly themes were designed for opaque background.

**Comment by bluz71** [comment]
@dbalatero,

Any progress on this issue? It would be good to solve this or close this if it is unfixable.

Do you have a series of repeatable steps I can test?

Cheers.

**Comment by dbalatero** [comment]
This is my Alacritty config: https://github.com/dbalatero/dotfiles/blob/master/alacritty.yml
(but I changed `background_opacity` to `1.0`, just haven't pushed yet).

I removed transparency in Alacritty but it's still blank:

![image](https://user-images.githubusercontent.com/59429/108405787-86587a80-71ef-11eb-850f-751c9d15a13a.png)

Steps I guess would be:
* open any Ruby file (`.rb`)
* add a `# TODO blah` comment
* it isn't highlighted

I think the change you made just removed the highlight color altogether, because I used to at least have a highlight before the change?

**Comment by bluz71** [comment]
I am an Alacritty user, so I will experiment with your settings to see if I can repeat your issue.

> I removed transparency in Alacritty but it's still blank:

Ok, something super weird is going on. Maybe something strange with your terminal setup.

Currently on my Alacritty setup `TODO`s are displayed just fine:

![todo](https://user-images.githubusercontent.com/11382509/108426938-86f51d80-7290-11eb-8e79-b2946ef16ec9.png)

What is the value of your `$TERM`? In my case I use the Alacritty terminfo, hence my `$TERM` is `alacritty`.


> I think the change you made just removed the highlight color altogether, because I used to at least have a highlight before the change?

The change merely explicity set the text color of `TODO`s, not the background color as noted in [the Git commit](https://github.com/bluz71/vim-nightfly-guicolors/commit/2ff9819204735f4e0252808e51c90eb26970075b)

Which version of Vim are you using? I am using Neovim 0.5 on Linux. If I use Vim 8.1 all is good as well.

Also, what does `:hi TODO` output? This is my result:

![todo2](https://user-images.githubusercontent.com/11382509/108427238-f8cd6700-7290-11eb-8291-56776e81cfdb.png)

Let's figure this out.

Cheers.

**Comment by bluz71** [comment]
With your Alacritty configuration I see the following:

![alacritty](https://user-images.githubusercontent.com/11382509/108432203-1e11a380-7298-11eb-8633-4a6b44c430c1.png)

All works.

I will do some experiments on my Macbook to see if that makes any difference.

I am using Alacritty 0.6.0 by the way; I haven't upgrade to 0.7.0 yet.

**Comment by bluz71** [comment]
A minimal `vimrc` file would also be handy.

Note, I just tested on my Macbook (Alacritty + Neovim), no issue with `TODO`.

Strange one. But let's try and fix it.

**Comment by dbalatero** [comment]
Ok, I restarted everything, reset tmux, reset my terminal, double checked that I updated your plugin, and it's working now.

![image](https://user-images.githubusercontent.com/59429/108605654-85f0e880-7383-11eb-9d2d-6c1a498ae5d7.png)

Something must have been stuck/cached in some Alacritty -> tmux -> vim layer, but I think I'm sorted now. Sorry for the churn!

**Comment by bluz71** [comment]
Ok, I am very happy that the issue cleared out.

But I am perplexed about what the actual cause was. It would have been quite useful to get the bottom. Alas this was a weird glitch of sorts. Maybe even non-reproduceable.

I appreciate the effort. We move on.

Best regards.
