### ISSUE TITLE
JSX tag colors

### ISSUE THREAD

**Issue by sleepyArpan** [bluz71/vim-nightfly-guicolors#19]
Hey, thanks for yet another great vim plugin. Have been really enjoying your library for plugins :) 
I wanted to ask, whether jsx tags, for opening and closing tags, being of different colors was a design decision you took while creating this color scheme? Note- I am currently using Neovim 0.4x with `vim-polygot` for syntax highlighting
![nightfly](https://user-images.githubusercontent.com/50901152/118791505-64d16280-b8b4-11eb-9be0-8be78857ad29.png)

**Comment by bluz71** [comment]
Yes, deliberate choice to distinguish opening and closing tags.
