### ISSUE TITLE
Iterm2 colorscheme

### ISSUE THREAD

**Issue by BlakeWilliams** [bluz71/vim-nightfly-guicolors#2]
I saw this colorscheme on trending and decided to give it a try and I've been really liking it so far!

I went ahead and made some pretty basic iterm2 colors locally so my terminal would match the theme. I wanted to contribute it back, but wanted to check if you were interested first, and if so, where the best place to put it would be.

I was thinking a `contrib` folder (or maybe a `nightfly-contrib` repo?) might make sense but didn't want to open a PR without getting your thoughts first.

Either way, thanks for sharing the theme!

**Comment by gguimaraesbr** [comment]
👍

**Comment by BlakeWilliams** [comment]
Sharing the one I made here just in case others come across this issue and want the iterm2 colors before it's possibly contributed upstream.

https://gist.github.com/BlakeWilliams/4e10b8856050a51b6d2ddb3b631059d9

**Comment by bluz71** [comment]
There does appear to be demand for matching terminal themes. So yes, I will add something in the coming days.

I will create and test _nightfly_ terminal themes for:

- iTerm2
- GNOME Terminal

Those are the two terminals I use on Mac and Linux.

However, I want to use and test them before committing them. Once I am happy I will add them to a new `terminal_themes` subdirectory. There are likely to be changes to the foreground and selection colors when compared to the Vim theme going by what I did with the moonfly terminal themes vs the Vim theme.

I will keep this issue open till then.

Cheers.

**Comment by bluz71** [comment]
Done.

- [iTerm2 nightfly theme](https://github.com/bluz71/vim-nightfly-guicolors/blob/master/terminal_themes/nightfly.itermcolors)

- [GNOME Terminal Nightfly setup script](https://github.com/bluz71/vim-nightfly-guicolors/blob/master/terminal_themes/gnome-terminal-nightfly.sh)
