### ISSUE TITLE
Doesn't work with simple ~/.vimrc

### ISSUE THREAD

**Issue by pbrilius** [bluz71/vim-nightfly-guicolors#21]
```shell
zshconfig
```
The output:
```shell
Error detected while processing /home/povilasb/.vimrc:
line    1:
E488: Trailing characters: # pbgroupeu
line    3:
E492: Not an editor command: Plug 'bluz71/vim-nightfly-guicolors'
line    4:
E492: Not an editor command: :PlugInstall
line    6:
E185: Cannot find color scheme 'nightfly'
Press ENTER or type command to continue
```

Following the **official** this _bistro_ main branch configuration.

**Comment by bluz71** [comment]
You first need to install a plugin manager, such as [vim-plug](https://github.com/junegunn/vim-plug), then you can install this colorscheme via that plugin manager. Go look at the vim-plug installation documentation.
