### ISSUE TITLE
barbar.nvim numbers have wrong colors

### ISSUE THREAD

**Issue by ecosse3** [bluz71/vim-nightfly-guicolors#26]
Hi,

Nightfly color scheme is my favorite one and I am working with that for over than year already and always had this kind of issue that number colors in barbar.nvim are wrong and have some rectangles around.

![2021-09-13_17-24](https://user-images.githubusercontent.com/17691791/133111740-57b0fc58-e951-46a0-98f0-2671320cc29d.png)

When I switch to some another split and current one becomes inactive:
![2021-09-13_17-25](https://user-images.githubusercontent.com/17691791/133111847-78b2c50e-12f3-4c69-8874-40238b07764a.png)

Is there a way to fix it? I have the same problem on Linux and macOS.

**Comment by bluz71** [comment]
Hello,

I don't use barbar.nvim myself, so this issue slipped through the cracks. The colors themselves were a third-party addition via PR #12 

The colors that were incorrect were barbar `Index` colors. I just committed a fix. I think your issue should now be resolved.

I appreciate the nice words about this colorscheme, I am happy that a few people like it.

Best regards.
