### ISSUE TITLE
Support nvim-cmp's custom menu

### ISSUE THREAD

**Issue by hrsh7th** [bluz71/vim-nightfly-guicolors#27]
I'm implementing it. But I don't familiar with vim's highlight and plugin integrations.

So I want feedback me the current approach is good or not.

https://github.com/hrsh7th/nvim-cmp/pull/224

Best regards.

**Comment by bluz71** [comment]
I do use nvim-cmp.
I have been waiting for that PR.

It seems you want me to test that PR. Ok, over the next couple days I will experiment, once I can free up time. Maybe in a few days you will hear from me.

Keep up the good work, I think your PR will be excellent.

Cheers.

**Comment by bluz71** [comment]
Hello @hrsh7th,

The scrollbar colour of your custom window I believe is not ideal.

See this screenshot for your custom menu:

<img width="499" alt="ScreenShot" src="https://user-images.githubusercontent.com/11382509/134792200-6644ff79-5400-4da4-9efa-47ab91c5b6d8.png">

The colour of the scrollbar is blue, which is the `PmenuSel` color.
The colour used should actually be, for my colorscheme, grey, which is the `PmenuSbar` color (Sbar short for scrollbar).

See this image of the native completion menu with the correct scrollbar color:

<img width="342" alt="ScreenShot2" src="https://user-images.githubusercontent.com/11382509/134792267-8cef47e0-2bdc-4ec8-83ad-ec837b0ba606.png">

With my other colorscheme, moonfly, this scrollbar color problem is more ugly:

<img width="449" alt="ScreenShot3" src="https://user-images.githubusercontent.com/11382509/134792310-2efee74d-e3de-41fc-bfd0-23a282960754.png">

Using `PmenuSbar` would solve this issue for my colorschemes.

Regards.

**Comment by hrsh7th** [comment]
Thank you. I will fix it.

**Comment by bluz71** [comment]
Thanks, that will help.

Currently, the new custom float mostly looks like the existing completion menu. However, what I really want is for something that looks like the Telescope fuzzy finder. That being a window which uses the standard editor background colour with a simple border. Maybe not the default, but I would sure love an option to create that look.

Will that be possible?

**Comment by hrsh7th** [comment]
It's definitely possible. I will consider customization API for it.

**Comment by bluz71** [comment]
> It's definitely possible. I will consider customization API for it.

Fantastic. I think that will be the ultimate, stealthy, look (like Telescope here):

<img width="596" alt="Screen Shot 2021-09-26 at 2 27 23 pm" src="https://user-images.githubusercontent.com/11382509/134793684-915f5caa-c98b-4458-8acc-3720af16ae63.png">

Anyway, in the meantime I have just committed a couple customisations for your upcoming floating completion menu. As mentioned, the scrollbar needs fixing at your end. Otherwise, from my end I am satisfied. I will resolve this.

Cheers.

**Comment by bluz71** [comment]
Just tested, thanks for the scrollbar fix. Looks much better.
