### ISSUE TITLE
VSCode / IntelliJ support

### ISSUE THREAD

**Issue by natsumi** [bluz71/vim-nightfly-guicolors#3]
Awesome theme.

Any chances of a VSCode / IntelliJ port?

**Comment by bluz71** [comment]
Sorry no, I am strictly a Vim/Neovim user only.

However, Nightfly is heavily based on Sarah Drasner's Night Owl theme, which she wrote for VSCode. So just use Night Owl:

- [Night Owl](https://github.com/sdras/night-owl-vscode-theme) for VS Code

- [Night Owl](https://github.com/xdrop/night-owl-jetbrains) for Jetbrains IDEs
