### ISSUE TITLE
Disable airline theme?

### ISSUE THREAD

**Issue by eemax** [bluz71/vim-nightfly-guicolors#30]
Love your theme. Keep it up!

Is there a way to disable the colorscheme for airline since it automatically loads?

**Comment by bluz71** [comment]
Not that I am aware of from my end, airline uses auto theme loading.

I would assume that you should be able to set a specific airline theme in your config which overrides the default. If not, speak with the airline developers.

From my side I don't think there is anything I can do. But I would also be confident that there will be a workaround available.

**Comment by eemax** [comment]
I solved with the following in my init.vim:
let g:airline_theme = 'default'

**Comment by bluz71** [comment]
Excellent.
