### ISSUE TITLE
Disruptive changes in treesitter

### ISSUE THREAD

**Issue by uga-rosa** [bluz71/vim-nightfly-guicolors#37]
There has been a major change in treesitter and some of the highlighting (e.g. the built-in function: require, pcall, etc.) has gone wrong.

![image](https://user-images.githubusercontent.com/82267684/196106146-e9928e47-e73e-4494-8b06-675be30b119a.png)

**Comment by bluz71** [comment]
This issue should now be fixed in the latest commit.

Cheers.
