### ISSUE TITLE
colorscheme nightfly not found

### ISSUE THREAD

**Issue by gmmoose20** [bluz71/vim-nightfly-guicolors#38]
I got this error after updating my plugins

![image](https://user-images.githubusercontent.com/62541303/197746647-64bc2910-5238-471e-b930-ef74db084cec.png)

**Comment by pallymore** [comment]
same issue here - i'm using NeoVim 0.8

**Comment by bluz71** [comment]
Very strange, in my Neovim 0.8 setup I can do `vim.api_nvim_set_hl(0, "TermCursor", { bg = "#222222", fg = "bg" })` with no issues, but in your case it errors out. It works for me on Linus and macOS.

The `fg = "bg"` appears to break.

What platform are you on?

Anyway, I have replaced such usages with real RGB codes, hence I believe this issue should now be resolved.

Apologies for the breakage; I am moving some VimScript to Lua (in this theme); so there may be some teething issues.

**Comment by pallymore** [comment]
I can confirm it works again now, thank you for the quick fix! 

I'm using Linux (Amazon Linux 2 x86_64)
