### ISSUE TITLE
`g:nightflyTransparent` is not working

### ISSUE THREAD

**Issue by gamoutatsumi** [bluz71/vim-nightfly-guicolors#40]
Related to #38

`g:nightflyTransparent` is breaking by changed color definition in now [commit](https://github.com/bluz71/vim-nightfly-guicolors/commit/ae43d6c72a990a6f48863466f0d3f100ef3d589a).

This problem is caused by defined `bg=NONE` in vim script.

So, needs define as "constants" colors in lua script to fix this.

My workaround is [here](https://github.com/gamoutatsumi/vim-nightfly-guicolors/commit/6c3cb39dc73bcfc689000b24a0de1c522381c4d9).

**Comment by bluz71** [comment]
Thanks for the code snippet.

This issue should be fixed; test it out and let me know if there are any issues.

Apologies for breaking this colorscheme, I am moving some Neovim logic to Lua, and there have been some speed-bumps.

**Comment by gamoutatsumi** [comment]
hmm...
It's looking working also previous commit.
I may have misunderstood.
Anyway, now it works. thanks for fix!
