### ISSUE TITLE
JavaScript syntax is not displaying the right colors

### ISSUE THREAD

**Issue by guilhermedeandrade** [bluz71/vim-nightfly-guicolors#7]
I've just installed the theme and the colors for JavaScript aren't matching the ones on the READEME screenshot:

<img width="654" alt="image" src="https://user-images.githubusercontent.com/8797405/77834383-523e1c00-713c-11ea-8ec8-22067c84cdfd.png">

I'm using kitty terminal, `NVIM v0.4.3`, [pangloss/vim-javascript](https://github.com/pangloss/vim-javascript) for syntax and I have `set termguicolors` in my `init.vim` file. Any ideas on what is happening here?

Thanks for the theme @bluz71, it looks amazing!

**Comment by bluz71** [comment]
Very strange. Most of the colors are correct except the import statement and numbers. I have no idea what's going on here.

I am an iTerm2 user on Mac and GNOME Terminal user on Linux. No issues.

I just downloaded and installed Kitty on Mac (Catalina), and all is fine for me (Kitty 0.17.2) with Neovim 0.4.3.

Try using a different terminal temporarily, maybe the GPU rendering of Kitty is doing something weird on your setup? Try normal Vim as well. I just want to see if the colorscheme works with different combinations.

**Comment by guilhermedeandrade** [comment]
You won't believe it! The issue was simply a `setbackground=light` command which I was using for my older theme. I'm so sorry for the trouble. I will close the issue. Thanks for your reply

**Comment by bluz71** [comment]
Interesting.

Note, inside the `nightfly` color scheme I do `set background=dark`.
You must have set it to `light` after the plugin had loaded.

Well spotted.
