### ISSUE TITLE
Not working in vim on iterm2

### ISSUE THREAD

**Issue by cr** [bluz71/vim-nightfly-guicolors#8]
**Problem description**
Colors are off in _vim 8.2_ on _iTerm2 3.3.9_.

**STR**
```
❯ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 29 2020 01:33:43)
❯ git clone git clone https://github.com/bluz71/vim-nightfly-guicolors.git ~/.vim/pack/vendor/start/vim-nightfly-guicolors
```

.vimrc:
```
set termguicolors
colorscheme nightfly
```
**Expected result**

nightfly color scheme glory

**Actual result**

Colors change, but are awfully off. Looks like an approximation by closest match from the 256 color palette.

![vimcolors](https://user-images.githubusercontent.com/170331/81582354-3c18b200-93b0-11ea-8880-ec764e814bdc.png)

**Comment by bluz71** [comment]
I use Vim/Neovim on iTerm2 with no issue.

Please make sure Preference / Profiles / Terminal / Report terminal type is set to `xterm-256color`.

**Comment by cr** [comment]
Thanks for looking into this! Terminal type is (and has) been `xterm-256color`. From memory, the iTerm prefs I tweaked were font, ansi colorscheme, subpixel rendering, and scrollback buffer. I don't think I changed anything essential, but if you think it's worth investigating, I'll have a look.

I also double checked that it's none of the other vim plugins on my side. The off-color effect also occurs with fresh .vim/.vimrc.

I'm happy to take any pointers for debugging and introspection.

**Comment by bluz71** [comment]
Try Neovim if you can, it would help a lot.

I don’t know why it is failing. Maybe try to minimise your vimrc as far as you can.

**Comment by cr** [comment]
nvim shows the same false colors, so I guess it's something about my iTerm config or environment.

![Screenshot 2020-05-12 at 10 26 02](https://user-images.githubusercontent.com/170331/81660448-0ec51600-943b-11ea-9957-9d1a6c4467c2.png)

**Comment by bluz71** [comment]
Colors in that image like kind-of right.

Are you sure the nightfly colors are wrong in your terminal?

Try Macvim, if you haven’t already.

**Comment by cr** [comment]
Well.

<img width="208" alt="pfp" src="https://user-images.githubusercontent.com/170331/81664857-3b2f6100-9440-11ea-8c93-a1c3b9f8b778.png">

In my defense I need to say that my screen makes the background look like it remains black, and I just wasn't expecting all the browns, but rather reds and beiges.

Close comparison of the screenshots still show slight off-grade coloring, but that's likely due to difference in color profiling.

<img width="693" alt="Screenshot 2020-05-12 at 10 59 38" src="https://user-images.githubusercontent.com/170331/81664718-09b69580-9440-11ea-9e41-51961fca501d.png">

Thank you and I am sorry for wasting your time.

**Comment by bluz71** [comment]
I believe iTerm2 does some very subtle colour tinting itself, maybe from one colour space to RGB. But it is subtle, so I never bothered to create an issue.

Anyone, glad to hear you are up and running.
